### PR TITLE
Added python support

### PR DESCRIPTION
**Pull request by jimray**
Hello. I'm quite a fan of what you've done here as I'm also a fan of Vagrant and Heroku.

However, my weapons of choice are Python and Django and I found the default build was missing some parts. So, I've tried to help fix that.

Specifically, I've added a few bits to the postinstall script to include python setup and dev tools as well as virtualenv and a rather minimal configuration to make all of that work out of the box for python devs.

I've also included Foreman to make the VM work even more like Heroku, in that it respects a project's Procfile and .env configuration

I've done a little bit of testing locally, it seems to work pretty well out of the box. I hope this will make the VM even that much better.

### CODE REVIEW

**Comment by ejholmes** [comment]
Awesome! Thanks!

**Comment by jimray** [comment]
My pleasure.

I assume someone will replace the .box file on Dropbox. Anything I can do to help with that?

Thanks again for building this, it really is great and quite handy.

**Comment by ejholmes** [comment]
I'll try to get the box rebuilt tonight.

**Comment by ejholmes** [comment]
The new box has been built and uploaded. Cheers!

**Comment by jimray** [comment]
Huzzah!

**Pull request merged**
