### PR TITLE
updating box for what's current with heroku

### PR DESCRIPTION
**Pull request by scottmuc**
Working with a team I noticed their heroku cedar stack was 64bit ubuntu, postgresql 9.1.3 and ruby patch level was p290.

### CODE REVIEW

**Comment by ejholmes** [comment]
Hmm, I'm all for changing the Ubuntu distro to 64bit and ruby to p290 but I'm a little hesitant to change postgres until the new [postgres dev](https://addons.heroku.com/heroku-postgresql) addon is the default database.

**Comment by scottmuc** [comment]
So base heroku instances still have postgres? Should the base box really have that then? Perhaps having cookbooks for heroku add-ons would be a good way to manage that. I can drop the current pull request and create more granular pull requests for the other changes.

btw, love this idea!

**Comment by ejholmes** [comment]
Base instances don't have postgres, but if you push a ruby app to heroku, a postgres 8.3.1x database will be provisioned automatically, so I'd still like to keep that as the default for now. If the version of postgres needs to be changed to accomodate postgres 9.x, then that should be done through Chef recipes or a bash script in the `Vagrantfile`.

Individual pull requests would be much appreciated for the other changes. Thanks!

**Comment by scottmuc** [comment]
I got an e-mail about this issue, but it's not showing up here. I'm confused :-)

"I think the heroku base OS for cedar may have changed. See output from a new cedar instance below:

```
heroku run bash
python
import platform
platform.platform()
'Linux-3.8.11-ec2-x86_64-with-debian-squeeze-sid'
```

I only noticed because my pandoc binary stopped working."

**Comment by puterleat** [comment]
Yeah I'm slightly confused too. I added it as a comment initially but deleted that and made a main issue because I thought it would get lost i'm still having this issue though. 

Ben

**Comment by scottmuc** [comment]
Strange, I don't see an issue on the main issue list either. Please retry adding the issue to the Github project.

**Pull request closed without merging**
